#!/usr/bin/env sh
time rsync --recursive --update --delete --links --hard-links --safe-links --perms --times --stats --exclude '.DS_Store' --exclude '.fseventsd' --exclude '.Trashes' --exclude '.metadata_never_index' /Volumes/fnl/ ~/Documents
